import Link from "next/link";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="p-8">
        {/* need to make into component and abstract */}
        <nav>
          <Link href={"#"}>Link here </Link>
        </nav>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
